"""
REAL REPOSITORY-MODE E2E TEST
==============================
This script validates the full repository acquisition pipeline:
  Repository URL -> project -> repo acquisition -> git clone -> package.json discovery
  -> real artifact -> scan -> graph -> snapshot -> report -> download

RULES:
  - NO manual package.json upload
  - NO artifact_id injection
  - NO manifest content submission
  - Scan triggered with ONLY scan_type (no artifact_id)
"""
import httpx
import asyncio
import json
import time
import sys

BASE_URL = "http://127.0.0.1:8001"
REPO_URL = "https://github.com/expressjs/express.git"
EXPECTED_DEPS = ["accepts", "body-parser", "cookie", "debug", "depd"]
DEMO_LEAK_MARKERS = ["example-project", "fake-react-app"]

async def run():
    async with httpx.AsyncClient(base_url=BASE_URL, timeout=120.0) as c:
        # ---- STEP 1: Register + Login ----
        email = f"repo_mode_e2e_{int(time.time())}@test.com"
        reg = await c.post("/api/v1/auth/register", json={
            "name": "Repo Mode E2E",
            "company": "Provenance Corp",
            "email": email,
            "password": "StrongPass123!",
        })
        print(f"[REGISTER] {reg.status_code}")

        login = await c.post("/api/v1/auth/login", json={
            "email": email, "password": "StrongPass123!"
        })
        assert login.status_code == 200, f"Login failed: {login.text}"
        token = login.json()["access_token"]
        headers = {"Authorization": f"Bearer {token}"}
        print(f"[LOGIN] OK - token received")

        # ---- STEP 2: Create Project with repository_url ----
        proj_resp = await c.post("/api/v1/projects", headers=headers, json={
            "name": f"express-repo-mode-{int(time.time())}",
            "description": "Real repository acquisition E2E",
            "language": "JavaScript",
            "visibility": "PRIVATE",
            "branch": "master",
            "url": REPO_URL
        })
        assert proj_resp.status_code == 201, f"Project creation failed: {proj_resp.text}"
        project = proj_resp.json()
        project_id = project["id"]
        print(f"[PROJECT] ID={project_id}")
        print(f"[PROJECT] repository_url={project.get('url', project.get('repository_url', 'N/A'))}")

        # ---- STEP 3: Trigger Repository Scan (NO artifact_id) ----
        # The backend MUST acquire manifest via RepositoryAcquisitionService
        print(f"\n[SCAN] Triggering repository acquisition scan (NO artifact_id)...")
        scan_resp = await c.post(f"/api/v1/projects/{project_id}/scans", headers=headers, json={
            "scan_type": "FULL"
            # INTENTIONALLY NO artifact_id - backend must clone
        })
        assert scan_resp.status_code == 201, f"Scan trigger failed: {scan_resp.text}"
        scan = scan_resp.json()
        scan_id = scan["id"]
        artifact_id = scan.get("artifact_id")
        print(f"[SCAN] ID={scan_id}")
        print(f"[SCAN] Status={scan['status']}")
        print(f"[SCAN] Artifact ID (generated by acquisition)={artifact_id}")
        assert artifact_id is not None, "PROVENANCE FAIL: Scan has no artifact_id - RepositoryAcquisitionService may not have run"

        # ---- STEP 4: Wait for scan completion ----
        print(f"\n[SCAN WAIT] Polling for completion...")
        final_scan = None
        for i in range(60):
            await asyncio.sleep(5)
            st = await c.get(f"/api/v1/projects/{project_id}/scans/{scan_id}", headers=headers)
            status = st.json()["status"]
            print(f"  Poll {i+1}: {status}")
            if status in ["COMPLETED", "FAILED"]:
                final_scan = st.json()
                break

        assert final_scan is not None, "Scan did not complete in time"
        assert final_scan["status"] == "COMPLETED", f"Scan FAILED: {final_scan.get('error_message')}"
        print(f"[SCAN] COMPLETED - total_dependencies={final_scan.get('total_dependencies')}")

        # ---- STEP 5: Check graph (dependency provenance) ----
        print(f"\n[GRAPH] Fetching dependency graph for project {project_id}...")
        graph_resp = await c.get(f"/api/v1/projects/{project_id}/graph", headers=headers)
        assert graph_resp.status_code == 200, f"Graph fetch failed: {graph_resp.text}"
        graph = graph_resp.json()
        nodes = graph.get("nodes", [])
        dep_names = [n.get("label", "").lower() for n in nodes]
        print(f"[GRAPH] Total nodes: {len(nodes)}")
        print(f"[GRAPH] Sample deps: {dep_names[:10]}")

        # Verify no demo data leak
        for marker in DEMO_LEAK_MARKERS:
            assert marker not in dep_names, f"PROVENANCE FAIL: Demo marker '{marker}' found in dependencies!"

        # Verify expected Express dependencies exist
        found_express_deps = [d for d in EXPECTED_DEPS if d in dep_names]
        print(f"[GRAPH] Expected Express deps found: {found_express_deps}")
        assert len(found_express_deps) >= 3, f"PROVENANCE FAIL: Expected Express deps not found. Got: {dep_names[:20]}"
        print(f"[GRAPH] PROVENANCE OK - Real Express dependencies confirmed")

        # Check for react (allowed if genuinely in snapshot but should not be there for Express)
        react_present = "react" in dep_names
        if react_present:
            print(f"[GRAPH] WARNING: 'react' found in dependencies - verify this is real express dependency, not demo data")
        else:
            print(f"[GRAPH] OK: 'react' not present (expected for express.js)")

        # ---- STEP 6: Generate JSON report ----
        print(f"\n[REPORT] Generating JSON report from scan {scan_id}...")
        report_resp = await c.post(f"/api/v1/projects/{project_id}/reports", headers=headers, json={
            "scan_id": scan_id,
            "format": "JSON"
        })
        assert report_resp.status_code == 201, f"Report creation failed: {report_resp.text}"
        report = report_resp.json()
        report_id = report["id"]
        print(f"[REPORT] ID={report_id}")

        # Wait for report completion
        for i in range(30):
            await asyncio.sleep(3)
            r = await c.get(f"/api/v1/projects/{project_id}/reports/{report_id}", headers=headers)
            status = r.json()["status"]
            print(f"  Report poll {i+1}: {status}")
            if status in ["COMPLETED", "FAILED"]:
                break

        final_report = (await c.get(f"/api/v1/projects/{project_id}/reports/{report_id}", headers=headers)).json()
        assert final_report["status"] == "COMPLETED", f"Report generation FAILED"
        print(f"[REPORT] COMPLETED")

        # Download JSON report
        dl_resp = await c.get(f"/api/v1/projects/{project_id}/reports/{report_id}/download", headers=headers)
        assert dl_resp.status_code == 200, f"Download failed: {dl_resp.status_code}"
        report_data = dl_resp.json()
        report_sections = report_data.get("sections", [])
        report_section_titles = [s["title"] for s in report_sections]
        print(f"[REPORT] Sections ({len(report_sections)}): {report_section_titles}")
        assert len(report_sections) == 16, f"Expected 16 sections, got {len(report_sections)}"
        print(f"[REPORT] All 16 sections present")

        # Verify provenance chain in report
        metadata = report_data.get("metadata", {})
        print(f"\n[PROVENANCE CHAIN]")
        print(f"  Repository URL: {REPO_URL}")
        print(f"  Project ID:     {project_id}")
        print(f"  Artifact ID:    {artifact_id} (generated by RepositoryAcquisitionService)")
        print(f"  Scan ID:        {scan_id}")
        print(f"  Report ID:      {report_id}")
        print(f"  Snapshot SHA256: {metadata.get('snapshot_sha256', 'N/A')}")
        print(f"  Dependency count: {len(nodes)}")
        print(f"  React present: {react_present}")

        # ---- STEP 7: Generate PDF report ----
        print(f"\n[PDF REPORT] Generating...")
        pdf_resp = await c.post(f"/api/v1/projects/{project_id}/reports", headers=headers, json={
            "scan_id": scan_id,
            "format": "PDF"
        })
        assert pdf_resp.status_code == 201, f"PDF report creation failed: {pdf_resp.text}"
        pdf_report_id = pdf_resp.json()["id"]
        for i in range(30):
            await asyncio.sleep(3)
            r = await c.get(f"/api/v1/projects/{project_id}/reports/{pdf_report_id}", headers=headers)
            status = r.json()["status"]
            if status in ["COMPLETED", "FAILED"]:
                break

        pdf_dl = await c.get(f"/api/v1/projects/{project_id}/reports/{pdf_report_id}/download", headers=headers)
        assert pdf_dl.status_code == 200, f"PDF Download failed: {pdf_dl.status_code}"
        pdf_bytes = len(pdf_dl.content)
        print(f"[PDF REPORT] Downloaded {pdf_bytes} bytes")
        assert pdf_bytes > 1000, f"PDF too small ({pdf_bytes} bytes), likely empty"

        # ---- FINAL SUMMARY ----
        print(f"\n{'='*60}")
        print(f"REPOSITORY-MODE E2E: ALL PROVENANCE INVARIANTS MET")
        print(f"{'='*60}")
        print(f"P0 Status: PASS")
        print(f"\nRuntime IDs (from REAL repository acquisition):")
        print(f"  Project ID:    {project_id}")
        print(f"  Artifact ID:   {artifact_id}")
        print(f"  Scan ID:       {scan_id}")
        print(f"  Report ID:     {report_id}")
        print(f"  PDF Report ID: {pdf_report_id}")
        print(f"\nDependency integrity:")
        print(f"  Total nodes:        {len(nodes)}")
        print(f"  Demo data present:  NO")
        print(f"  React present:      {react_present}")
        print(f"  Express deps found: {found_express_deps}")

        # Save results for audit
        with open("repo_mode_e2e_result.json", "w") as f:
            json.dump({
                "status": "PASS",
                "project_id": project_id,
                "artifact_id": artifact_id,
                "scan_id": scan_id,
                "report_id": report_id,
                "pdf_report_id": pdf_report_id,
                "dependency_count": len(nodes),
                "react_present": react_present,
                "express_deps_found": found_express_deps,
                "sections_count": len(report_sections),
                "pdf_bytes": pdf_bytes,
                "snapshot_sha256": metadata.get("snapshot_sha256"),
            }, f, indent=2)
        print(f"\nResults saved to repo_mode_e2e_result.json")

if __name__ == "__main__":
    asyncio.run(run())
