"""Add generation_token to ReportArtifact

Revision ID: 266652f986b5
Revises: 69c29f3cbc47
Create Date: 2026-08-30 21:17:13.436435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '266652f986b5'
down_revision: Union[str, None] = '69c29f3cbc47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_artifacts', sa.Column('generation_token', sa.String(length=64), nullable=True, comment='Tracks which generation attempt produced this artifact. Used for stale artifact reconciliation.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_artifacts', 'generation_token')
    # ### end Alembic commands ###
