"""add report intelligence tables

Revision ID: 59d769c3e465
Revises: e2f3g4h5i6j7
Create Date: 2026-08-29 12:57:12.335702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59d769c3e465'
down_revision: Union[str, None] = 'e2f3g4h5i6j7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=True, comment='The scan this report is based on. Nullable to allow reports to survive scan pruning.'),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.Enum('SECURITY_REPORT', 'PACKAGE_REPORT', 'EXECUTIVE_REPORT', 'COMPLIANCE_REPORT', name='report_type_enum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'GENERATING', 'COMPLETED', 'FAILED', 'EXPIRED', 'DELETED', name='report_status_enum', native_enum=False), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_organization_id'), 'reports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_reports_project_id'), 'reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_reports_scan_id'), 'reports', ['scan_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('report_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('format', sa.Enum('JSON', 'HTML', 'PDF', 'CSV', 'SARIF', name='report_format_enum', native_enum=False), nullable=False),
    sa.Column('encrypted_data', postgresql.BYTEA(), nullable=False),
    sa.Column('dek_ciphertext', sa.String(length=500), nullable=True, comment='Fallback if not using dedicated encryption metadata table, but metadata table is preferred.'),
    sa.Column('artifact_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('artifact_sha256', sa.String(length=64), nullable=False, comment='SHA-256 checksum of the encrypted artifact blob'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'format', name='uq_report_artifact_format')
    )
    op.create_index(op.f('ix_report_artifacts_report_id'), 'report_artifacts', ['report_id'], unique=False)
    op.create_table('report_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('snapshot_sha256', sa.String(length=64), nullable=False, comment='SHA-256 checksum of the canonical plaintext JSON snapshot'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_snapshots_report_id'), 'report_snapshots', ['report_id'], unique=True)
    op.create_table('report_encryption_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('encryption_version', sa.String(length=20), nullable=False),
    sa.Column('key_reference', sa.String(length=255), nullable=False, comment='External KMS Key Identifier / Vault Key Name'),
    sa.Column('initialization_vector', sa.String(length=64), nullable=False, comment='Base64 encoded IV / Nonce'),
    sa.Column('authentication_tag', sa.String(length=64), nullable=False, comment='Base64 encoded GCM authentication tag'),
    sa.Column('encrypted_dek_reference', sa.String(length=500), nullable=False, comment='Base64 encoded encrypted Data Encryption Key'),
    sa.Column('checksum', sa.String(length=64), nullable=False, comment='SHA-256 checksum of the ciphertext'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['report_artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_encryption_metadata_artifact_id'), 'report_encryption_metadata', ['artifact_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_encryption_metadata_artifact_id'), table_name='report_encryption_metadata')
    op.drop_table('report_encryption_metadata')
    op.drop_index(op.f('ix_report_snapshots_report_id'), table_name='report_snapshots')
    op.drop_table('report_snapshots')
    op.drop_index(op.f('ix_report_artifacts_report_id'), table_name='report_artifacts')
    op.drop_table('report_artifacts')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_scan_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_project_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_organization_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
