"""Increase audit action enum length

Revision ID: 69c29f3cbc47
Revises: 79039bf2cec5
Create Date: 2026-08-30 20:35:43.597361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69c29f3cbc47'
down_revision: Union[str, None] = '79039bf2cec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('USER_LOGIN', 'USER_LOGOUT', 'PROJECT_CREATED', 'PROJECT_UPDATED', 'PROJECT_DELETED', 'PROJECT_UPLOADED', 'ARTIFACT_CREATED', 'SCAN_STARTED', 'SCAN_COMPLETED', 'SCAN_FAILED', 'FINDING_UPDATED', 'MEMBER_ADDED', 'MEMBER_REMOVED', 'ROLE_CHANGED', 'REPORT_CREATED', 'REPORT_GENERATION_STARTED', 'REPORT_GENERATION_COMPLETED', 'REPORT_GENERATION_FAILED', 'REPORT_DOWNLOADED', 'REPORT_RETRY_REQUESTED', 'REPORT_DELETED', 'REPORT_EXPIRED', name='audit_action_enum', native_enum=False, length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'action',
               existing_type=sa.Enum('USER_LOGIN', 'USER_LOGOUT', 'PROJECT_CREATED', 'PROJECT_UPDATED', 'PROJECT_DELETED', 'PROJECT_UPLOADED', 'ARTIFACT_CREATED', 'SCAN_STARTED', 'SCAN_COMPLETED', 'SCAN_FAILED', 'FINDING_UPDATED', 'MEMBER_ADDED', 'MEMBER_REMOVED', 'ROLE_CHANGED', 'REPORT_CREATED', 'REPORT_GENERATION_STARTED', 'REPORT_GENERATION_COMPLETED', 'REPORT_GENERATION_FAILED', 'REPORT_DOWNLOADED', 'REPORT_RETRY_REQUESTED', 'REPORT_DELETED', 'REPORT_EXPIRED', name='audit_action_enum', native_enum=False, length=64),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###
