"""add report generation lifecycle

Revision ID: 79039bf2cec5
Revises: deac8928b8ea
Create Date: 2026-08-30 00:00:16.667652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79039bf2cec5'
down_revision: Union[str, None] = 'deac8928b8ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('generation_started_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the current or most recent generation attempt'))
    op.add_column('reports', sa.Column('error_category', sa.String(length=100), nullable=True, comment='Safe categorical failure reason'))
    op.add_column('reports', sa.Column('attempt_count', sa.Integer(), nullable=False))
    op.add_column('reports', sa.Column('worker_id', sa.String(length=100), nullable=True, comment='Identity of the worker currently claiming the report'))
    op.add_column('reports', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the current worker lease expires'))
    op.add_column('reports', sa.Column('generation_token', sa.String(length=36), nullable=True, comment='Unique token for the current claim to prevent split-brain'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'generation_token')
    op.drop_column('reports', 'lease_expires_at')
    op.drop_column('reports', 'worker_id')
    op.drop_column('reports', 'attempt_count')
    op.drop_column('reports', 'error_category')
    op.drop_column('reports', 'generation_started_at')
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
