"""0001_initial_database_schema

Revision ID: b1ae584b89a0
Revises: 
Create Date: 2026-08-17 14:55:49.810513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1ae584b89a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('spdx_identifier', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('PERMISSIVE', 'COPYLEFT', 'WEAK_COPYLEFT', 'PROPRIETARY', 'UNKNOWN', name='license_category_enum', native_enum=False), nullable=False),
    sa.Column('risk_level', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', 'UNKNOWN', name='license_risk_level_enum', native_enum=False), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licenses_spdx_identifier'), 'licenses', ['spdx_identifier'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('package_ecosystems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('default_package_manager', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_ecosystems_name'), 'package_ecosystems', ['name'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email_active', 'users', ['email'], unique=False)
    op.create_index('idx_users_username_active', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vulnerabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vulnerability_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.Enum('NVD', 'OSV', 'GITHUB_ADVISORY', 'CISA', 'VENDOR_ADVISORY', 'OTHER', name='vulnerability_source_enum', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', 'UNKNOWN', name='severity_level_enum', native_enum=False), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affected_packages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerabilities_severity'), 'vulnerabilities', ['severity'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_vulnerability_id'), 'vulnerabilities', ['vulnerability_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('USER_LOGIN', 'USER_LOGOUT', 'PROJECT_CREATED', 'PROJECT_UPDATED', 'PROJECT_DELETED', 'PROJECT_UPLOADED', 'ARTIFACT_CREATED', 'SCAN_STARTED', 'SCAN_COMPLETED', 'SCAN_FAILED', 'FINDING_UPDATED', 'MEMBER_ADDED', 'MEMBER_REMOVED', 'ROLE_CHANGED', name='audit_action_enum', native_enum=False), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_org_created', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('organization_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INVITED', 'SUSPENDED', name='member_status_enum', native_enum=False), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_member')
    )
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_role_id'), 'organization_members', ['role_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('repository_url', sa.String(length=500), nullable=True),
    sa.Column('repository_provider', sa.Enum('GITHUB', 'GITLAB', 'BITBUCKET', 'LOCAL', 'API', 'OTHER', name='repository_provider_enum', native_enum=False), nullable=False),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('project_type', sa.Enum('WEB', 'MOBILE', 'BACKEND', 'DESKTOP', 'LIBRARY', 'MONOREPO', 'OTHER', name='project_type_enum', native_enum=False), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('visibility', sa.Enum('PRIVATE', 'ORGANIZATION', name='project_visibility_enum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'DEPRECATED', name='project_status_enum', native_enum=False), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_org_project_slug')
    )
    op.create_index('idx_projects_org_status', 'projects', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False, comment='One-way cryptographic hash of the refresh token'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_tokens_user_active', 'refresh_tokens', ['user_id', 'revoked_at', 'expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('security_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Policy rules: max_critical_vulnerabilities, allow_copyleft, etc.'),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_policies_org_active', 'security_policies', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_security_policies_organization_id'), 'security_policies', ['organization_id'], unique=False)
    op.create_table('project_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('UPLOAD', 'GIT', 'GITHUB', 'GITLAB', 'BITBUCKET', 'API', name='artifact_source_type_enum', native_enum=False), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_provider', sa.String(length=50), nullable=False),
    sa.Column('storage_bucket', sa.String(length=100), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('encrypted_storage_key', sa.String(length=500), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('upload_status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'FAILED', 'QUARANTINED', 'DELETED', name='artifact_upload_status_enum', native_enum=False), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('is_immutable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version_number', name='uq_project_artifact_version')
    )
    op.create_index('idx_artifacts_project_created', 'project_artifacts', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_project_artifacts_content_hash'), 'project_artifacts', ['content_hash'], unique=False)
    op.create_index(op.f('ix_project_artifacts_project_id'), 'project_artifacts', ['project_id'], unique=False)
    op.create_table('artifact_encryption_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('encryption_version', sa.String(length=20), nullable=False),
    sa.Column('key_reference', sa.String(length=255), nullable=False, comment='External KMS Key Identifier / Vault Key Name'),
    sa.Column('initialization_vector', sa.String(length=64), nullable=False, comment='Base64 encoded IV / Nonce'),
    sa.Column('authentication_tag', sa.String(length=64), nullable=False, comment='Base64 encoded GCM authentication tag'),
    sa.Column('encrypted_dek_reference', sa.String(length=500), nullable=False, comment='Base64 encoded encrypted Data Encryption Key'),
    sa.Column('checksum', sa.String(length=64), nullable=False, comment='SHA-256 checksum of the ciphertext'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['project_artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_encryption_metadata_artifact_id'), 'artifact_encryption_metadata', ['artifact_id'], unique=True)
    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('initiated_by', sa.UUID(), nullable=True),
    sa.Column('scan_type', sa.Enum('FULL', 'QUICK', 'SECURITY', 'DEPENDENCY', 'LICENSE', 'MANUAL', 'SCHEDULED', name='scan_type_enum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'INITIALIZING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='scan_status_enum', native_enum=False), nullable=False),
    sa.Column('scanner_version', sa.String(length=50), nullable=False),
    sa.Column('scanner_commit', sa.String(length=40), nullable=True),
    sa.Column('ruleset_version', sa.String(length=50), nullable=True),
    sa.Column('vulnerability_database_version', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('total_dependencies', sa.Integer(), nullable=False),
    sa.Column('direct_dependencies', sa.Integer(), nullable=False),
    sa.Column('transitive_dependencies', sa.Integer(), nullable=False),
    sa.Column('vulnerable_dependencies', sa.Integer(), nullable=False),
    sa.Column('outdated_dependencies', sa.Integer(), nullable=False),
    sa.Column('license_issues', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['project_artifacts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scans_artifact_status', 'scans', ['artifact_id', 'status'], unique=False)
    op.create_index('idx_scans_project_created', 'scans', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_scans_artifact_id'), 'scans', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_scans_project_id'), 'scans', ['project_id'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_table('analysis_workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=True),
    sa.Column('workspace_identifier', sa.String(length=100), nullable=False),
    sa.Column('storage_reference', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'EXTRACTING', 'READY', 'ANALYZING', 'CLEANUP_PENDING', 'DESTROYED', 'FAILED', name='workspace_status_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('destroyed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['project_artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_identifier')
    )
    op.create_index('idx_workspaces_status_expires', 'analysis_workspaces', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_analysis_workspaces_artifact_id'), 'analysis_workspaces', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_analysis_workspaces_scan_id'), 'analysis_workspaces', ['scan_id'], unique=False)
    op.create_table('dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('ecosystem_id', sa.UUID(), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('package_version', sa.String(length=100), nullable=False),
    sa.Column('version_constraint', sa.String(length=100), nullable=True),
    sa.Column('dependency_type', sa.Enum('RUNTIME', 'DEVELOPMENT', 'OPTIONAL', 'PEER', 'BUILD', 'UNKNOWN', name='dependency_type_enum', native_enum=False), nullable=False),
    sa.Column('is_direct', sa.Boolean(), nullable=False),
    sa.Column('is_transitive', sa.Boolean(), nullable=False),
    sa.Column('package_manager', sa.String(length=50), nullable=True),
    sa.Column('manifest_file', sa.String(length=500), nullable=True),
    sa.Column('lockfile', sa.String(length=500), nullable=True),
    sa.Column('license', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ecosystem_id'], ['package_ecosystems.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'ecosystem_id', 'package_name', 'package_version', name='uq_scan_pkg_version')
    )
    op.create_index('idx_dependencies_scan_pkg', 'dependencies', ['scan_id', 'package_name'], unique=False)
    op.create_index(op.f('ix_dependencies_ecosystem_id'), 'dependencies', ['ecosystem_id'], unique=False)
    op.create_index(op.f('ix_dependencies_package_name'), 'dependencies', ['package_name'], unique=False)
    op.create_index(op.f('ix_dependencies_project_id'), 'dependencies', ['project_id'], unique=False)
    op.create_index(op.f('ix_dependencies_scan_id'), 'dependencies', ['scan_id'], unique=False)
    op.create_table('dependency_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('parent_dependency_id', sa.UUID(), nullable=False),
    sa.Column('child_dependency_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('DIRECT', 'TRANSITIVE', 'PEER', 'OPTIONAL', 'DEV', name='relationship_type_enum', native_enum=False), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_dependency_id'], ['dependencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_dependency_id'], ['dependencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'parent_dependency_id', 'child_dependency_id', name='uq_dependency_edge')
    )
    op.create_index('idx_dep_edges_parent_child', 'dependency_edges', ['parent_dependency_id', 'child_dependency_id'], unique=False)
    op.create_index(op.f('ix_dependency_edges_child_dependency_id'), 'dependency_edges', ['child_dependency_id'], unique=False)
    op.create_index(op.f('ix_dependency_edges_parent_dependency_id'), 'dependency_edges', ['parent_dependency_id'], unique=False)
    op.create_index(op.f('ix_dependency_edges_scan_id'), 'dependency_edges', ['scan_id'], unique=False)
    op.create_table('dependency_licenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dependency_id', sa.UUID(), nullable=False),
    sa.Column('license_id', sa.UUID(), nullable=False),
    sa.Column('detected_expression', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dependency_id', 'license_id', name='uq_dep_license')
    )
    op.create_index(op.f('ix_dependency_licenses_dependency_id'), 'dependency_licenses', ['dependency_id'], unique=False)
    op.create_index(op.f('ix_dependency_licenses_license_id'), 'dependency_licenses', ['license_id'], unique=False)
    op.create_table('dependency_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dependency_id', sa.UUID(), nullable=False),
    sa.Column('current_version', sa.String(length=100), nullable=False),
    sa.Column('latest_version', sa.String(length=100), nullable=False),
    sa.Column('recommended_version', sa.String(length=100), nullable=True),
    sa.Column('version_status', sa.Enum('UP_TO_DATE', 'OUTDATED', 'MAJOR_UPDATE', 'MINOR_UPDATE', 'PATCH_UPDATE', 'UNKNOWN', name='version_status_enum', native_enum=False), nullable=False),
    sa.Column('release_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependency_versions_dependency_id'), 'dependency_versions', ['dependency_id'], unique=True)
    op.create_table('dependency_vulnerabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('dependency_id', sa.UUID(), nullable=False),
    sa.Column('vulnerability_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', 'UNKNOWN', name='severity_level_enum', native_enum=False), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'FALSE_POSITIVE', 'RESOLVED', 'ACCEPTED_RISK', name='finding_resolution_status_enum', native_enum=False), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'dependency_id', 'vulnerability_id', name='uq_scan_dep_vuln')
    )
    op.create_index('idx_dep_vulns_scan_status', 'dependency_vulnerabilities', ['scan_id', 'status'], unique=False)
    op.create_index(op.f('ix_dependency_vulnerabilities_dependency_id'), 'dependency_vulnerabilities', ['dependency_id'], unique=False)
    op.create_index(op.f('ix_dependency_vulnerabilities_scan_id'), 'dependency_vulnerabilities', ['scan_id'], unique=False)
    op.create_index(op.f('ix_dependency_vulnerabilities_vulnerability_id'), 'dependency_vulnerabilities', ['vulnerability_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('dependency_id', sa.UUID(), nullable=True),
    sa.Column('vulnerability_id', sa.UUID(), nullable=True),
    sa.Column('finding_type', sa.Enum('VULNERABILITY', 'OUTDATED_DEPENDENCY', 'LICENSE_RISK', 'SECURITY_POLICY', 'CONFIGURATION', 'DEPENDENCY_CONFLICT', 'UNKNOWN', name='finding_type_enum', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', 'UNKNOWN', name='finding_severity_enum', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'RESOLVED', 'IGNORED', 'FALSE_POSITIVE', name='unified_finding_status_enum', native_enum=False), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependencies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_findings_org_severity_status', 'findings', ['organization_id', 'severity', 'status'], unique=False)
    op.create_index('idx_findings_project_type', 'findings', ['project_id', 'finding_type'], unique=False)
    op.create_index(op.f('ix_findings_dependency_id'), 'findings', ['dependency_id'], unique=False)
    op.create_index(op.f('ix_findings_finding_type'), 'findings', ['finding_type'], unique=False)
    op.create_index(op.f('ix_findings_organization_id'), 'findings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_findings_project_id'), 'findings', ['project_id'], unique=False)
    op.create_index(op.f('ix_findings_scan_id'), 'findings', ['scan_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_index(op.f('ix_findings_vulnerability_id'), 'findings', ['vulnerability_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_vulnerability_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_scan_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_project_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_organization_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_finding_type'), table_name='findings')
    op.drop_index(op.f('ix_findings_dependency_id'), table_name='findings')
    op.drop_index('idx_findings_project_type', table_name='findings')
    op.drop_index('idx_findings_org_severity_status', table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_dependency_vulnerabilities_vulnerability_id'), table_name='dependency_vulnerabilities')
    op.drop_index(op.f('ix_dependency_vulnerabilities_scan_id'), table_name='dependency_vulnerabilities')
    op.drop_index(op.f('ix_dependency_vulnerabilities_dependency_id'), table_name='dependency_vulnerabilities')
    op.drop_index('idx_dep_vulns_scan_status', table_name='dependency_vulnerabilities')
    op.drop_table('dependency_vulnerabilities')
    op.drop_index(op.f('ix_dependency_versions_dependency_id'), table_name='dependency_versions')
    op.drop_table('dependency_versions')
    op.drop_index(op.f('ix_dependency_licenses_license_id'), table_name='dependency_licenses')
    op.drop_index(op.f('ix_dependency_licenses_dependency_id'), table_name='dependency_licenses')
    op.drop_table('dependency_licenses')
    op.drop_index(op.f('ix_dependency_edges_scan_id'), table_name='dependency_edges')
    op.drop_index(op.f('ix_dependency_edges_parent_dependency_id'), table_name='dependency_edges')
    op.drop_index(op.f('ix_dependency_edges_child_dependency_id'), table_name='dependency_edges')
    op.drop_index('idx_dep_edges_parent_child', table_name='dependency_edges')
    op.drop_table('dependency_edges')
    op.drop_index(op.f('ix_dependencies_scan_id'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_project_id'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_package_name'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_ecosystem_id'), table_name='dependencies')
    op.drop_index('idx_dependencies_scan_pkg', table_name='dependencies')
    op.drop_table('dependencies')
    op.drop_index(op.f('ix_analysis_workspaces_scan_id'), table_name='analysis_workspaces')
    op.drop_index(op.f('ix_analysis_workspaces_artifact_id'), table_name='analysis_workspaces')
    op.drop_index('idx_workspaces_status_expires', table_name='analysis_workspaces')
    op.drop_table('analysis_workspaces')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_project_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_artifact_id'), table_name='scans')
    op.drop_index('idx_scans_project_created', table_name='scans')
    op.drop_index('idx_scans_artifact_status', table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_artifact_encryption_metadata_artifact_id'), table_name='artifact_encryption_metadata')
    op.drop_table('artifact_encryption_metadata')
    op.drop_index(op.f('ix_project_artifacts_project_id'), table_name='project_artifacts')
    op.drop_index(op.f('ix_project_artifacts_content_hash'), table_name='project_artifacts')
    op.drop_index('idx_artifacts_project_created', table_name='project_artifacts')
    op.drop_table('project_artifacts')
    op.drop_index(op.f('ix_security_policies_organization_id'), table_name='security_policies')
    op.drop_index('idx_policies_org_active', table_name='security_policies')
    op.drop_table('security_policies')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_user_active', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index('idx_projects_org_status', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_role_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_org_created', table_name='audit_logs')
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_vulnerabilities_vulnerability_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_severity'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_username_active', table_name='users')
    op.drop_index('idx_users_email_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_package_ecosystems_name'), table_name='package_ecosystems')
    op.drop_table('package_ecosystems')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_licenses_spdx_identifier'), table_name='licenses')
    op.drop_table('licenses')
    # ### end Alembic commands ###
