"""Increase scan status length

Revision ID: da5c2fa7e1aa
Revises: b1ae584b89a0
Create Date: 2026-08-23 22:08:45.264942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da5c2fa7e1aa'
down_revision: Union[str, None] = 'b1ae584b89a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scans', 'status',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('QUEUED', 'INITIALIZING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'PROVIDER_UNAVAILABLE', name='scan_status_enum', native_enum=False, length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scans', 'status',
               existing_type=sa.Enum('QUEUED', 'INITIALIZING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'PROVIDER_UNAVAILABLE', name='scan_status_enum', native_enum=False, length=50),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###
