"""add report generation intent

Revision ID: deac8928b8ea
Revises: 59d769c3e465
Create Date: 2026-08-29 23:46:32.689282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'deac8928b8ea'
down_revision: Union[str, None] = '59d769c3e465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('format', sa.Enum('JSON', 'HTML', 'PDF', 'CSV', 'SARIF', name='report_format_enum', native_enum=False), nullable=False))
    op.create_unique_constraint('uq_report_project_scan_type_format', 'reports', ['project_id', 'scan_id', 'report_type', 'format'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_report_project_scan_type_format', 'reports', type_='unique')
    op.drop_column('reports', 'format')
    # ### end Alembic commands ###
