/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PasswordResetSuccessRouteImport } from './routes/password-reset-success'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ServerErrorRouteImport } from './routes/server-error'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ShellAuditLogsRouteImport } from './routes/_shell.audit-logs'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellGraphRouteImport } from './routes/_shell.graph'
import { Route as ShellHealthAnalysisRouteImport } from './routes/_shell.health-analysis'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellScannerRouteImport } from './routes/_shell.scanner'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellSystemHealthRouteImport } from './routes/_shell.system-health'
import { Route as ShellUsersRouteImport } from './routes/_shell.users'
import { Route as ShellVulnerabilitiesRouteImport } from './routes/_shell.vulnerabilities'
import { Route as ShellPackagesIndexRouteImport } from './routes/_shell.packages.index'
import { Route as ShellPackagesPackageIdRouteImport } from './routes/_shell.packages.$packageId'
import { Route as ShellRepositoriesIndexRouteImport } from './routes/_shell.repositories.index'
import { Route as ShellRepositoriesRepoIdRouteImport } from './routes/_shell.repositories.$repoId'
import { Route as ShellRepositoriesNewRouteImport } from './routes/_shell.repositories.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetSuccessRoute = PasswordResetSuccessRouteImport.update({
  id: '/password-reset-success',
  path: '/password-reset-success',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerErrorRoute = ServerErrorRouteImport.update({
  id: '/server-error',
  path: '/server-error',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAuditLogsRoute = ShellAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGraphRoute = ShellGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHealthAnalysisRoute = ShellHealthAnalysisRouteImport.update({
  id: '/health-analysis',
  path: '/health-analysis',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellScannerRoute = ShellScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSystemHealthRoute = ShellSystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUsersRoute = ShellUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVulnerabilitiesRoute = ShellVulnerabilitiesRouteImport.update({
  id: '/vulnerabilities',
  path: '/vulnerabilities',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPackagesIndexRoute = ShellPackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPackagesPackageIdRoute = ShellPackagesPackageIdRouteImport.update({
  id: '/packages/$packageId',
  path: '/packages/$packageId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRepositoriesIndexRoute = ShellRepositoriesIndexRouteImport.update({
  id: '/repositories/',
  path: '/repositories/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRepositoriesRepoIdRoute = ShellRepositoriesRepoIdRouteImport.update({
  id: '/repositories/$repoId',
  path: '/repositories/$repoId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRepositoriesNewRoute = ShellRepositoriesNewRouteImport.update({
  id: '/repositories/new',
  path: '/repositories/new',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/password-reset-success': typeof PasswordResetSuccessRoute
  '/register': typeof RegisterRoute
  '/server-error': typeof ServerErrorRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/welcome': typeof WelcomeRoute
  '/audit-logs': typeof ShellAuditLogsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/graph': typeof ShellGraphRoute
  '/health-analysis': typeof ShellHealthAnalysisRoute
  '/reports': typeof ShellReportsRoute
  '/scanner': typeof ShellScannerRoute
  '/settings': typeof ShellSettingsRoute
  '/system-health': typeof ShellSystemHealthRoute
  '/users': typeof ShellUsersRoute
  '/vulnerabilities': typeof ShellVulnerabilitiesRoute
  '/packages/$packageId': typeof ShellPackagesPackageIdRoute
  '/repositories/$repoId': typeof ShellRepositoriesRepoIdRoute
  '/repositories/new': typeof ShellRepositoriesNewRoute
  '/packages/': typeof ShellPackagesIndexRoute
  '/repositories/': typeof ShellRepositoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/password-reset-success': typeof PasswordResetSuccessRoute
  '/register': typeof RegisterRoute
  '/server-error': typeof ServerErrorRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/welcome': typeof WelcomeRoute
  '/audit-logs': typeof ShellAuditLogsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/graph': typeof ShellGraphRoute
  '/health-analysis': typeof ShellHealthAnalysisRoute
  '/reports': typeof ShellReportsRoute
  '/scanner': typeof ShellScannerRoute
  '/settings': typeof ShellSettingsRoute
  '/system-health': typeof ShellSystemHealthRoute
  '/users': typeof ShellUsersRoute
  '/vulnerabilities': typeof ShellVulnerabilitiesRoute
  '/packages/$packageId': typeof ShellPackagesPackageIdRoute
  '/repositories/$repoId': typeof ShellRepositoriesRepoIdRoute
  '/repositories/new': typeof ShellRepositoriesNewRoute
  '/packages': typeof ShellPackagesIndexRoute
  '/repositories': typeof ShellRepositoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/password-reset-success': typeof PasswordResetSuccessRoute
  '/register': typeof RegisterRoute
  '/server-error': typeof ServerErrorRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/welcome': typeof WelcomeRoute
  '/_shell/audit-logs': typeof ShellAuditLogsRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/graph': typeof ShellGraphRoute
  '/_shell/health-analysis': typeof ShellHealthAnalysisRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/scanner': typeof ShellScannerRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/system-health': typeof ShellSystemHealthRoute
  '/_shell/users': typeof ShellUsersRoute
  '/_shell/vulnerabilities': typeof ShellVulnerabilitiesRoute
  '/_shell/packages/$packageId': typeof ShellPackagesPackageIdRoute
  '/_shell/repositories/$repoId': typeof ShellRepositoriesRepoIdRoute
  '/_shell/repositories/new': typeof ShellRepositoriesNewRoute
  '/_shell/packages/': typeof ShellPackagesIndexRoute
  '/_shell/repositories/': typeof ShellRepositoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/forgot-password'
    | '/login'
    | '/password-reset-success'
    | '/register'
    | '/server-error'
    | '/verify-otp'
    | '/welcome'
    | '/audit-logs'
    | '/dashboard'
    | '/graph'
    | '/health-analysis'
    | '/reports'
    | '/scanner'
    | '/settings'
    | '/system-health'
    | '/users'
    | '/vulnerabilities'
    | '/packages/$packageId'
    | '/repositories/$repoId'
    | '/repositories/new'
    | '/packages/'
    | '/repositories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/forgot-password'
    | '/login'
    | '/password-reset-success'
    | '/register'
    | '/server-error'
    | '/verify-otp'
    | '/welcome'
    | '/audit-logs'
    | '/dashboard'
    | '/graph'
    | '/health-analysis'
    | '/reports'
    | '/scanner'
    | '/settings'
    | '/system-health'
    | '/users'
    | '/vulnerabilities'
    | '/packages/$packageId'
    | '/repositories/$repoId'
    | '/repositories/new'
    | '/packages'
    | '/repositories'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/forbidden'
    | '/forgot-password'
    | '/login'
    | '/password-reset-success'
    | '/register'
    | '/server-error'
    | '/verify-otp'
    | '/welcome'
    | '/_shell/audit-logs'
    | '/_shell/dashboard'
    | '/_shell/graph'
    | '/_shell/health-analysis'
    | '/_shell/reports'
    | '/_shell/scanner'
    | '/_shell/settings'
    | '/_shell/system-health'
    | '/_shell/users'
    | '/_shell/vulnerabilities'
    | '/_shell/packages/$packageId'
    | '/_shell/repositories/$repoId'
    | '/_shell/repositories/new'
    | '/_shell/packages/'
    | '/_shell/repositories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PasswordResetSuccessRoute: typeof PasswordResetSuccessRoute
  RegisterRoute: typeof RegisterRoute
  ServerErrorRoute: typeof ServerErrorRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset-success': {
      id: '/password-reset-success'
      path: '/password-reset-success'
      fullPath: '/password-reset-success'
      preLoaderRoute: typeof PasswordResetSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-error': {
      id: '/server-error'
      path: '/server-error'
      fullPath: '/server-error'
      preLoaderRoute: typeof ServerErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/audit-logs': {
      id: '/_shell/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof ShellAuditLogsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/graph': {
      id: '/_shell/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof ShellGraphRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/health-analysis': {
      id: '/_shell/health-analysis'
      path: '/health-analysis'
      fullPath: '/health-analysis'
      preLoaderRoute: typeof ShellHealthAnalysisRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/scanner': {
      id: '/_shell/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ShellScannerRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/system-health': {
      id: '/_shell/system-health'
      path: '/system-health'
      fullPath: '/system-health'
      preLoaderRoute: typeof ShellSystemHealthRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/users': {
      id: '/_shell/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ShellUsersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/vulnerabilities': {
      id: '/_shell/vulnerabilities'
      path: '/vulnerabilities'
      fullPath: '/vulnerabilities'
      preLoaderRoute: typeof ShellVulnerabilitiesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/packages/': {
      id: '/_shell/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof ShellPackagesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/packages/$packageId': {
      id: '/_shell/packages/$packageId'
      path: '/packages/$packageId'
      fullPath: '/packages/$packageId'
      preLoaderRoute: typeof ShellPackagesPackageIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/repositories/': {
      id: '/_shell/repositories/'
      path: '/repositories'
      fullPath: '/repositories/'
      preLoaderRoute: typeof ShellRepositoriesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/repositories/$repoId': {
      id: '/_shell/repositories/$repoId'
      path: '/repositories/$repoId'
      fullPath: '/repositories/$repoId'
      preLoaderRoute: typeof ShellRepositoriesRepoIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/repositories/new': {
      id: '/_shell/repositories/new'
      path: '/repositories/new'
      fullPath: '/repositories/new'
      preLoaderRoute: typeof ShellRepositoriesNewRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAuditLogsRoute: typeof ShellAuditLogsRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellGraphRoute: typeof ShellGraphRoute
  ShellHealthAnalysisRoute: typeof ShellHealthAnalysisRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellScannerRoute: typeof ShellScannerRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellSystemHealthRoute: typeof ShellSystemHealthRoute
  ShellUsersRoute: typeof ShellUsersRoute
  ShellVulnerabilitiesRoute: typeof ShellVulnerabilitiesRoute
  ShellPackagesPackageIdRoute: typeof ShellPackagesPackageIdRoute
  ShellRepositoriesRepoIdRoute: typeof ShellRepositoriesRepoIdRoute
  ShellRepositoriesNewRoute: typeof ShellRepositoriesNewRoute
  ShellPackagesIndexRoute: typeof ShellPackagesIndexRoute
  ShellRepositoriesIndexRoute: typeof ShellRepositoriesIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAuditLogsRoute: ShellAuditLogsRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellGraphRoute: ShellGraphRoute,
  ShellHealthAnalysisRoute: ShellHealthAnalysisRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellScannerRoute: ShellScannerRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellSystemHealthRoute: ShellSystemHealthRoute,
  ShellUsersRoute: ShellUsersRoute,
  ShellVulnerabilitiesRoute: ShellVulnerabilitiesRoute,
  ShellPackagesPackageIdRoute: ShellPackagesPackageIdRoute,
  ShellRepositoriesRepoIdRoute: ShellRepositoriesRepoIdRoute,
  ShellRepositoriesNewRoute: ShellRepositoriesNewRoute,
  ShellPackagesIndexRoute: ShellPackagesIndexRoute,
  ShellRepositoriesIndexRoute: ShellRepositoriesIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PasswordResetSuccessRoute: PasswordResetSuccessRoute,
  RegisterRoute: RegisterRoute,
  ServerErrorRoute: ServerErrorRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
